// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGqDhOlVnbMKU1ftkXf3UfuelicK-uAYI',
    appId: '1:600025639536:web:c40ba3158542bfcf9462b5',
    messagingSenderId: '600025639536',
    projectId: 'travenor-87442',
    authDomain: 'travenor-87442.firebaseapp.com',
    storageBucket: 'travenor-87442.appspot.com',
    measurementId: 'G-CE1HWCELGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSysUsm_r-SI1dF_90I6o-NFvYKr3qnus',
    appId: '1:600025639536:android:507d28bc12d472129462b5',
    messagingSenderId: '600025639536',
    projectId: 'travenor-87442',
    storageBucket: 'travenor-87442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1RYWwc5-StgCa1TkB_QA8e9OsJi2qLmo',
    appId: '1:600025639536:ios:5202c108d6d2c3129462b5',
    messagingSenderId: '600025639536',
    projectId: 'travenor-87442',
    storageBucket: 'travenor-87442.appspot.com',
    iosBundleId: 'com.titoparissapplication.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1RYWwc5-StgCa1TkB_QA8e9OsJi2qLmo',
    appId: '1:600025639536:ios:8abad6f1db87387d9462b5',
    messagingSenderId: '600025639536',
    projectId: 'travenor-87442',
    storageBucket: 'travenor-87442.appspot.com',
    iosBundleId: 'com.titoparissapplication.travenor.RunnerTests',
  );
}
